name: "package-json-version"
description: "Change the version of your projects package.json file in a simple GitHub action."
branding:
  icon: 'server'
  color: 'blue'
inputs:
  version:
    description: "This will be the version you want to set in the package.json file"
    required: true
  package:
    description: "The location of the package.json file, defaults to current directory."
    default: "./"
    required: true
  git-tag-version:
    description: "If set to true, the version will be tagged and committed. Same behaviour as git-tag-version"
    default: false
    required: false

runs:
  using: "node18"
  main: "dist/index.js"
